version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"

  database:
    image: mariadb:10
    environment:
      MARIADB_ROOT_PASSWORD: blorg
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
